
### 
GET http://localhost:3000/user

### 
POST http://localhost:3000/user
Content-Type: application/json

{
  "nome": "",
  "email": "",
  "senha": 
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "",
  "senha": ""
}

### 
GET http://localhost:3000/user/1

### 
DELETE http://localhost:3000/user/1